// This file was generated by "LibDomTypeScriptParser, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", from "lib.dom.d.ts".
// Do not edit directly. If you encounter any bugs, please fix the generator's code.
//
// Copyright (C) 2022 Trung Nguyen. All rights reserved.
// Licensed under the MIT License.

/*! *****************************************************************************
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0

THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.

See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
***************************************************************************** */

#nullable enable
using System;
using System.Diagnostics.CodeAnalysis;
using Trungnt2910.Browser.Generators;

namespace Trungnt2910.Browser.Dom;

#pragma warning disable CS0108, CS8764, CS8766
/// <summary>
/// To be added.
/// </summary>
[JsObject]
public partial class CanvasFillStrokeStyles: JsObject, ICanvasFillStrokeStyles
{
    
    /// <summary>
    /// To be added.
    /// </summary>
    public Union<string, CanvasGradient, CanvasPattern>? FillStyle
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<Union<string, CanvasGradient, CanvasPattern>>.ValueOrNullFromJs($"{_jsThis}.fillStyle");
        set => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.fillStyle = {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(value))}");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public Union<string, CanvasGradient, CanvasPattern>? StrokeStyle
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<Union<string, CanvasGradient, CanvasPattern>>.ValueOrNullFromJs($"{_jsThis}.strokeStyle");
        set => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.strokeStyle = {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(value))}");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public CanvasGradient? CreateConicGradient(double? startAngle, double? x, double? y) => global::Trungnt2910.Browser.WebAssemblyRuntime<CanvasGradient>.ValueOrNullFromJs($"{_jsThis}.createConicGradient({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(startAngle))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(x))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(y))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public CanvasGradient? CreateLinearGradient(double? x0, double? y0, double? x1, double? y1) => global::Trungnt2910.Browser.WebAssemblyRuntime<CanvasGradient>.ValueOrNullFromJs($"{_jsThis}.createLinearGradient({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(x0))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(y0))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(x1))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(y1))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public CanvasPattern? CreatePattern(Union<HTMLImageElement, SVGImageElement, HTMLVideoElement, HTMLCanvasElement, ImageBitmap>? image, string? repetition) => global::Trungnt2910.Browser.WebAssemblyRuntime<CanvasPattern>.ValueOrNullFromJs($"{_jsThis}.createPattern({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(image))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(repetition))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public CanvasGradient? CreateRadialGradient(double? x0, double? y0, double? r0, double? x1, double? y1, double? r1) => global::Trungnt2910.Browser.WebAssemblyRuntime<CanvasGradient>.ValueOrNullFromJs($"{_jsThis}.createRadialGradient({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(x0))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(y0))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(r0))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(x1))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(y1))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(r1))})");
    
}
#pragma warning restore CS0108, CS8764, CS8766

