// This file was generated by "LibDomTypeScriptParser, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", from "lib.dom.d.ts".
// Do not edit directly. If you encounter any bugs, please fix the generator's code.
//
// Copyright (C) 2022 Trung Nguyen. All rights reserved.
// Licensed under the MIT License.

/*! *****************************************************************************
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0

THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.

See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
***************************************************************************** */

#nullable enable
using System;
using System.Diagnostics.CodeAnalysis;
using Trungnt2910.Browser.Generators;

namespace Trungnt2910.Browser.Dom;

#pragma warning disable CS0108, CS8764, CS8766
/// <summary>
/// A single CSS style sheet. It inherits properties and methods from its parent, StyleSheet.
/// </summary>
[JsObject]
public partial class CSSStyleSheet: StyleSheet
{
    
    /// <summary>
    /// To be added.
    /// </summary>
    public CSSRuleList? CssRules
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<CSSRuleList>.ValueOrNullFromJs($"{_jsThis}.cssRules");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public CSSRule? OwnerRule
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<CSSRule>.ValueOrNullFromJs($"{_jsThis}.ownerRule");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    [global::System.Obsolete]
    public CSSRuleList? Rules
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<CSSRuleList>.ValueOrNullFromJs($"{_jsThis}.rules");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    [global::System.Obsolete]
    public double? AddRule(string? selector, string? style, double? index) => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.addRule({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(selector))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(style))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(index))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public void DeleteRule(double? index) => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.deleteRule({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(index))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? InsertRule(string? rule, double? index) => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.insertRule({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(rule))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(index))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    [global::System.Obsolete]
    public void RemoveRule(double? index) => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.removeRule({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(index))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public Promise<CSSStyleSheet>? Replace(string? text) => global::Trungnt2910.Browser.WebAssemblyRuntime<Promise<CSSStyleSheet>>.ValueOrNullFromJs($"{_jsThis}.replace({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(text))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public void ReplaceSync(string? text) => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.replaceSync({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(text))})");
    
}
#pragma warning restore CS0108, CS8764, CS8766

