// This file was generated by "LibDomTypeScriptParser, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", from "lib.dom.d.ts".
// Do not edit directly. If you encounter any bugs, please fix the generator's code.
//
// Copyright (C) 2022 Trung Nguyen. All rights reserved.
// Licensed under the MIT License.

/*! *****************************************************************************
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0

THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.

See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
***************************************************************************** */

#nullable enable
using System;
using System.Diagnostics.CodeAnalysis;
using Trungnt2910.Browser.Generators;

namespace Trungnt2910.Browser.Dom;

#pragma warning disable CS0108, CS8764, CS8766
/// <summary>
/// An abnormal event (called an exception) which occurs as a result of calling a method or accessing a property of a web API.
/// </summary>
[JsObject]
public partial class DOMException: Error
{
    
    /// <summary>
    /// To be added.
    /// </summary>
    [global::System.Obsolete]
    public double? Code
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.code");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public string? Message
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.StringOrNullFromJs($"{_jsThis}.message");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public string? Name
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.StringOrNullFromJs($"{_jsThis}.name");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? ABORT_ERR
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.ABORT_ERR");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? DATA_CLONE_ERR
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.DATA_CLONE_ERR");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? DOMSTRING_SIZE_ERR
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.DOMSTRING_SIZE_ERR");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? HIERARCHY_REQUEST_ERR
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.HIERARCHY_REQUEST_ERR");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? INDEX_SIZE_ERR
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.INDEX_SIZE_ERR");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? INUSE_ATTRIBUTE_ERR
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.INUSE_ATTRIBUTE_ERR");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? INVALID_ACCESS_ERR
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.INVALID_ACCESS_ERR");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? INVALID_CHARACTER_ERR
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.INVALID_CHARACTER_ERR");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? INVALID_MODIFICATION_ERR
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.INVALID_MODIFICATION_ERR");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? INVALID_NODE_TYPE_ERR
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.INVALID_NODE_TYPE_ERR");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? INVALID_STATE_ERR
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.INVALID_STATE_ERR");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? NAMESPACE_ERR
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.NAMESPACE_ERR");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? NETWORK_ERR
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.NETWORK_ERR");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? NOT_FOUND_ERR
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.NOT_FOUND_ERR");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? NOT_SUPPORTED_ERR
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.NOT_SUPPORTED_ERR");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? NO_DATA_ALLOWED_ERR
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.NO_DATA_ALLOWED_ERR");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? NO_MODIFICATION_ALLOWED_ERR
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.NO_MODIFICATION_ALLOWED_ERR");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? QUOTA_EXCEEDED_ERR
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.QUOTA_EXCEEDED_ERR");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? SECURITY_ERR
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.SECURITY_ERR");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? SYNTAX_ERR
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.SYNTAX_ERR");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? TIMEOUT_ERR
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.TIMEOUT_ERR");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? TYPE_MISMATCH_ERR
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.TYPE_MISMATCH_ERR");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? URL_MISMATCH_ERR
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.URL_MISMATCH_ERR");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? VALIDATION_ERR
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.VALIDATION_ERR");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? WRONG_DOCUMENT_ERR
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.WRONG_DOCUMENT_ERR");
    }
    
}
#pragma warning restore CS0108, CS8764, CS8766

