// This file was generated by "LibDomTypeScriptParser, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", from "lib.dom.d.ts".
// Do not edit directly. If you encounter any bugs, please fix the generator's code.
//
// Copyright (C) 2022 Trung Nguyen. All rights reserved.
// Licensed under the MIT License.

/*! *****************************************************************************
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0

THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.

See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
***************************************************************************** */

#nullable enable
using System;
using System.Diagnostics.CodeAnalysis;
using Trungnt2910.Browser.Generators;

namespace Trungnt2910.Browser.Dom;

#pragma warning disable CS0108, CS8764, CS8766
/// <summary>
/// To be added.
/// </summary>
[JsObject]
public partial class DOMMatrixReadOnly: JsObject
{
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? A
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.a");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? B
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.b");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? C
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.c");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? D
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.d");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? E
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.e");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? F
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.f");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public bool? Is2D
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.boolOrNullFromJs($"{_jsThis}.is2D");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public bool? IsIdentity
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.boolOrNullFromJs($"{_jsThis}.isIdentity");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? M11
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.m11");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? M12
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.m12");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? M13
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.m13");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? M14
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.m14");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? M21
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.m21");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? M22
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.m22");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? M23
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.m23");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? M24
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.m24");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? M31
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.m31");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? M32
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.m32");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? M33
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.m33");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? M34
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.m34");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? M41
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.m41");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? M42
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.m42");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? M43
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.m43");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? M44
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.m44");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public DOMMatrix? FlipX() => global::Trungnt2910.Browser.WebAssemblyRuntime<DOMMatrix>.ValueOrNullFromJs($"{_jsThis}.flipX()");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public DOMMatrix? FlipY() => global::Trungnt2910.Browser.WebAssemblyRuntime<DOMMatrix>.ValueOrNullFromJs($"{_jsThis}.flipY()");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public DOMMatrix? Inverse() => global::Trungnt2910.Browser.WebAssemblyRuntime<DOMMatrix>.ValueOrNullFromJs($"{_jsThis}.inverse()");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public DOMMatrix? Multiply(DOMMatrixInit? other) => global::Trungnt2910.Browser.WebAssemblyRuntime<DOMMatrix>.ValueOrNullFromJs($"{_jsThis}.multiply({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(other))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public DOMMatrix? Rotate(double? rotX, double? rotY, double? rotZ) => global::Trungnt2910.Browser.WebAssemblyRuntime<DOMMatrix>.ValueOrNullFromJs($"{_jsThis}.rotate({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(rotX))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(rotY))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(rotZ))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public DOMMatrix? RotateAxisAngle(double? x, double? y, double? z, double? angle) => global::Trungnt2910.Browser.WebAssemblyRuntime<DOMMatrix>.ValueOrNullFromJs($"{_jsThis}.rotateAxisAngle({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(x))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(y))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(z))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(angle))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public DOMMatrix? RotateFromVector(double? x, double? y) => global::Trungnt2910.Browser.WebAssemblyRuntime<DOMMatrix>.ValueOrNullFromJs($"{_jsThis}.rotateFromVector({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(x))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(y))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public DOMMatrix? Scale(double? scaleX, double? scaleY, double? scaleZ, double? originX, double? originY, double? originZ) => global::Trungnt2910.Browser.WebAssemblyRuntime<DOMMatrix>.ValueOrNullFromJs($"{_jsThis}.scale({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(scaleX))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(scaleY))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(scaleZ))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(originX))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(originY))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(originZ))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public DOMMatrix? Scale3d(double? scale, double? originX, double? originY, double? originZ) => global::Trungnt2910.Browser.WebAssemblyRuntime<DOMMatrix>.ValueOrNullFromJs($"{_jsThis}.scale3d({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(scale))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(originX))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(originY))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(originZ))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    [global::System.Obsolete]
    public DOMMatrix? ScaleNonUniform(double? scaleX, double? scaleY) => global::Trungnt2910.Browser.WebAssemblyRuntime<DOMMatrix>.ValueOrNullFromJs($"{_jsThis}.scaleNonUniform({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(scaleX))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(scaleY))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public DOMMatrix? SkewX(double? sx) => global::Trungnt2910.Browser.WebAssemblyRuntime<DOMMatrix>.ValueOrNullFromJs($"{_jsThis}.skewX({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(sx))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public DOMMatrix? SkewY(double? sy) => global::Trungnt2910.Browser.WebAssemblyRuntime<DOMMatrix>.ValueOrNullFromJs($"{_jsThis}.skewY({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(sy))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public Float32Array? ToFloat32Array() => global::Trungnt2910.Browser.WebAssemblyRuntime<Float32Array>.ValueOrNullFromJs($"{_jsThis}.toFloat32Array()");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public Float64Array? ToFloat64Array() => global::Trungnt2910.Browser.WebAssemblyRuntime<Float64Array>.ValueOrNullFromJs($"{_jsThis}.toFloat64Array()");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public JsObject? ToJSON() => global::Trungnt2910.Browser.WebAssemblyRuntime<JsObject>.ValueOrNullFromJs($"{_jsThis}.toJSON()");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public DOMPoint? TransformPoint(DOMPointInit? point) => global::Trungnt2910.Browser.WebAssemblyRuntime<DOMPoint>.ValueOrNullFromJs($"{_jsThis}.transformPoint({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(point))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public DOMMatrix? Translate(double? tx, double? ty, double? tz) => global::Trungnt2910.Browser.WebAssemblyRuntime<DOMMatrix>.ValueOrNullFromJs($"{_jsThis}.translate({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(tx))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(ty))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(tz))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public override string? ToString() => global::Trungnt2910.Browser.WebAssemblyRuntime.StringOrNullFromJs($"{_jsThis}.toString()");
    
}
#pragma warning restore CS0108, CS8764, CS8766

