// This file was generated by "LibDomTypeScriptParser, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", from "lib.dom.d.ts".
// Do not edit directly. If you encounter any bugs, please fix the generator's code.
//
// Copyright (C) 2022 Trung Nguyen. All rights reserved.
// Licensed under the MIT License.

/*! *****************************************************************************
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0

THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.

See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
***************************************************************************** */

#nullable enable
using System;
using System.Diagnostics.CodeAnalysis;
using Trungnt2910.Browser.Generators;

namespace Trungnt2910.Browser.Dom;

#pragma warning disable CS0108, CS8764, CS8766
/// <summary>
/// Allows manipulation of the browser session history, that is the pages visited in the tab or frame that the current page is loaded in.
/// </summary>
[JsObject]
public partial class History: JsObject
{
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? Length
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.length");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public string? ScrollRestoration
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.StringOrNullFromJs($"{_jsThis}.scrollRestoration");
        set => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.scrollRestoration = {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(value))}");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public JsObject? State
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<JsObject>.ValueOrNullFromJs($"{_jsThis}.state");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public void Back() => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.back()");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public void Forward() => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.forward()");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public void Go(double? delta) => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.go({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(delta))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public void PushState(JsObject? data, string? unused, Union<string, URL>? url) => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.pushState({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(data))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(unused))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(url))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public void ReplaceState(JsObject? data, string? unused, Union<string, URL>? url) => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.replaceState({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(data))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(unused))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(url))})");
    
}
#pragma warning restore CS0108, CS8764, CS8766

