// This file was generated by "LibDomTypeScriptParser, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", from "lib.dom.d.ts".
// Do not edit directly. If you encounter any bugs, please fix the generator's code.
//
// Copyright (C) 2022 Trung Nguyen. All rights reserved.
// Licensed under the MIT License.

/*! *****************************************************************************
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0

THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.

See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
***************************************************************************** */

#nullable enable
using System;
using System.Diagnostics.CodeAnalysis;
using Trungnt2910.Browser.Generators;

namespace Trungnt2910.Browser.Dom;

#pragma warning disable CS0108, CS8764, CS8766
/// <summary>
/// This Intersection Observer API interface describes the intersection between the target element and its root container at a specific moment of transition.
/// </summary>
[JsObject]
public partial class IntersectionObserverEntry: JsObject
{
    
    /// <summary>
    /// To be added.
    /// </summary>
    public DOMRectReadOnly? BoundingClientRect
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<DOMRectReadOnly>.ValueOrNullFromJs($"{_jsThis}.boundingClientRect");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? IntersectionRatio
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.intersectionRatio");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public DOMRectReadOnly? IntersectionRect
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<DOMRectReadOnly>.ValueOrNullFromJs($"{_jsThis}.intersectionRect");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public bool? IsIntersecting
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.boolOrNullFromJs($"{_jsThis}.isIntersecting");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public DOMRectReadOnly? RootBounds
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<DOMRectReadOnly>.ValueOrNullFromJs($"{_jsThis}.rootBounds");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public Element? Target
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<Element>.ValueOrNullFromJs($"{_jsThis}.target");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? Time
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.time");
    }
    
}
#pragma warning restore CS0108, CS8764, CS8766

