// This file was generated by "LibDomTypeScriptParser, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", from "lib.dom.d.ts".
// Do not edit directly. If you encounter any bugs, please fix the generator's code.
//
// Copyright (C) 2023 Trung Nguyen. All rights reserved.
// Licensed under the MIT License.

/*! *****************************************************************************
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0

THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.

See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
***************************************************************************** */

#nullable enable
using System;
using System.Diagnostics.CodeAnalysis;
using Trungnt2910.Browser.Generators;

namespace Trungnt2910.Browser.Dom;

#pragma warning disable CS0108, CS8764, CS8766
/// <summary>
/// Provides access to connected media input devices like cameras and microphones, as well as screen sharing. In essence, it lets you obtain access to any hardware source of media data.
/// Available only in secure contexts.
/// </summary>
[JsObject]
public partial class MediaDevices: EventTarget
{
    
    /// <summary>
    /// To be added.
    /// </summary>
    public JsFunc<MediaDevices?, Event?, JsObject?>? OnDeviceChange
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<JsFunc<MediaDevices?, Event?, JsObject?>>.ValueOrNullFromJs($"{_jsThis}.ondevicechange");
        set => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.ondevicechange = {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(value))}");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public Promise<JsArray<MediaDeviceInfo>>? EnumerateDevices() => global::Trungnt2910.Browser.WebAssemblyRuntime<Promise<JsArray<MediaDeviceInfo>>>.ValueOrNullFromJs($"{_jsThis}.enumerateDevices()");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public Promise<MediaStream>? GetDisplayMedia(DisplayMediaStreamConstraints? constraints) => global::Trungnt2910.Browser.WebAssemblyRuntime<Promise<MediaStream>>.ValueOrNullFromJs($"{_jsThis}.getDisplayMedia({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(constraints))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public MediaTrackSupportedConstraints? GetSupportedConstraints() => global::Trungnt2910.Browser.WebAssemblyRuntime<MediaTrackSupportedConstraints>.ValueOrNullFromJs($"{_jsThis}.getSupportedConstraints()");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public Promise<MediaStream>? GetUserMedia(MediaStreamConstraints? constraints) => global::Trungnt2910.Browser.WebAssemblyRuntime<Promise<MediaStream>>.ValueOrNullFromJs($"{_jsThis}.getUserMedia({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(constraints))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public void AddEventListener(string? type, Union<EventListener, EventListenerObject>? listener, Union<bool, AddEventListenerOptions>? options) => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.addEventListener({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(type))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(listener))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(options))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public void RemoveEventListener(string? type, Union<EventListener, EventListenerObject>? listener, Union<bool, EventListenerOptions>? options) => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.removeEventListener({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(type))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(listener))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(options))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public event EventHandler<Event?> DeviceChange
    {
        add => AddEventListener("devicechange", value);
        remove => RemoveEventListener("devicechange", value);
    }
    
}
#pragma warning restore CS0108, CS8764, CS8766

