// This file was generated by "LibDomTypeScriptParser, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", from "lib.dom.d.ts".
// Do not edit directly. If you encounter any bugs, please fix the generator's code.
//
// Copyright (C) 2023 Trung Nguyen. All rights reserved.
// Licensed under the MIT License.

/*! *****************************************************************************
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0

THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.

See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
***************************************************************************** */

#nullable enable
using System;
using System.Diagnostics.CodeAnalysis;
using Trungnt2910.Browser.Generators;

namespace Trungnt2910.Browser.Dom;

#pragma warning disable CS0108, CS8764, CS8766
/// <summary>
/// Events that occur due to the user interacting with a pointing device (such as a mouse). Common events using this interface include click, dblclick, mouseup, mousedown.
/// </summary>
[JsObject]
public partial class MouseEvent: UIEvent
{
    
    /// <summary>
    /// To be added.
    /// </summary>
    public bool? AltKey
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.boolOrNullFromJs($"{_jsThis}.altKey");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? Button
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.button");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? Buttons
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.buttons");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? ClientX
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.clientX");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? ClientY
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.clientY");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public bool? CtrlKey
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.boolOrNullFromJs($"{_jsThis}.ctrlKey");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public bool? MetaKey
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.boolOrNullFromJs($"{_jsThis}.metaKey");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? MovementX
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.movementX");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? MovementY
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.movementY");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? OffsetX
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.offsetX");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? OffsetY
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.offsetY");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? PageX
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.pageX");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? PageY
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.pageY");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public EventTarget? RelatedTarget
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<EventTarget>.ValueOrNullFromJs($"{_jsThis}.relatedTarget");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? ScreenX
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.screenX");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? ScreenY
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.screenY");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public bool? ShiftKey
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.boolOrNullFromJs($"{_jsThis}.shiftKey");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? X
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.x");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? Y
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.y");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public bool? GetModifierState(string? keyArg) => global::Trungnt2910.Browser.WebAssemblyRuntime.boolOrNullFromJs($"{_jsThis}.getModifierState({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(keyArg))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    [global::System.Obsolete]
    public void InitMouseEvent(string? typeArg, bool? canBubbleArg, bool? cancelableArg, Window? viewArg, double? detailArg, double? screenXArg, double? screenYArg, double? clientXArg, double? clientYArg, bool? ctrlKeyArg, bool? altKeyArg, bool? shiftKeyArg, bool? metaKeyArg, double? buttonArg, IEventTarget? relatedTargetArg) => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.initMouseEvent({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(typeArg))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(canBubbleArg))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(cancelableArg))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(viewArg))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(detailArg))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(screenXArg))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(screenYArg))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(clientXArg))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(clientYArg))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(ctrlKeyArg))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(altKeyArg))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(shiftKeyArg))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(metaKeyArg))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(buttonArg))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(relatedTargetArg))})");
    
}
#pragma warning restore CS0108, CS8764, CS8766

