// This file was generated by "LibDomTypeScriptParser, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", from "lib.dom.d.ts".
// Do not edit directly. If you encounter any bugs, please fix the generator's code.
//
// Copyright (C) 2023 Trung Nguyen. All rights reserved.
// Licensed under the MIT License.

/*! *****************************************************************************
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0

THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.

See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
***************************************************************************** */

#nullable enable
using System;
using System.Diagnostics.CodeAnalysis;
using Trungnt2910.Browser.Generators;

namespace Trungnt2910.Browser.Dom;

#pragma warning disable CS0108, CS8764, CS8766
/// <summary>
/// A collection of Attr objects. Objects inside a NamedNodeMap are not in any particular order, unlike NodeList, although they may be accessed by an index as in an array.
/// </summary>
[JsObject]
public partial class NamedNodeMap: JsObject, global::System.Collections.Generic.IReadOnlyList<Attr?>
{
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? Length
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.length");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public Attr? GetNamedItem(string? qualifiedName) => global::Trungnt2910.Browser.WebAssemblyRuntime<Attr>.ValueOrNullFromJs($"{_jsThis}.getNamedItem({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(qualifiedName))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public Attr? GetNamedItemNS(string? @namespace, string? localName) => global::Trungnt2910.Browser.WebAssemblyRuntime<Attr>.ValueOrNullFromJs($"{_jsThis}.getNamedItemNS({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(@namespace))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(localName))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public Attr? Item(double? index) => global::Trungnt2910.Browser.WebAssemblyRuntime<Attr>.ValueOrNullFromJs($"{_jsThis}.item({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(index))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public Attr? RemoveNamedItem(string? qualifiedName) => global::Trungnt2910.Browser.WebAssemblyRuntime<Attr>.ValueOrNullFromJs($"{_jsThis}.removeNamedItem({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(qualifiedName))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public Attr? RemoveNamedItemNS(string? @namespace, string? localName) => global::Trungnt2910.Browser.WebAssemblyRuntime<Attr>.ValueOrNullFromJs($"{_jsThis}.removeNamedItemNS({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(@namespace))}, {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(localName))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public Attr? SetNamedItem(Attr? attr) => global::Trungnt2910.Browser.WebAssemblyRuntime<Attr>.ValueOrNullFromJs($"{_jsThis}.setNamedItem({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(attr))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public Attr? SetNamedItemNS(Attr? attr) => global::Trungnt2910.Browser.WebAssemblyRuntime<Attr>.ValueOrNullFromJs($"{_jsThis}.setNamedItemNS({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(attr))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    [global::System.Runtime.CompilerServices.IndexerName("Indexer")]
    public Attr? this[double index]
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<Attr>.ValueOrNullFromJs($"{_jsThis}[{(global::Trungnt2910.Browser.JsObject.ToJsObjectString(index))}]");
        set => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}[{(global::Trungnt2910.Browser.JsObject.ToJsObjectString(index))}] = {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(value))}");
    }
    
    
    /// <inheritdoc/>
    public int Count => global::Trungnt2910.Browser.WebAssemblyRuntime.Int32FromJs($"{_jsThis}.length");
    
    
    /// <inheritdoc/>
    [global::System.Runtime.CompilerServices.IndexerName("Indexer")]
    public Attr? this[int index] => global::Trungnt2910.Browser.WebAssemblyRuntime<Attr>.ValueOrNullFromJs($"{_jsThis}[{(global::Trungnt2910.Browser.JsObject.ToJsObjectString(index))}]");
    
    
    /// <inheritdoc/>
    public global::System.Collections.Generic.IEnumerator<Attr?> GetEnumerator() { for (int i = 0; i < Count; ++i) yield return this[i]; }
    
    
    /// <inheritdoc/>
    global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();
    
}
#pragma warning restore CS0108, CS8764, CS8766

