// This file was generated by "LibDomTypeScriptParser, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", from "lib.dom.d.ts".
// Do not edit directly. If you encounter any bugs, please fix the generator's code.
//
// Copyright (C) 2023 Trung Nguyen. All rights reserved.
// Licensed under the MIT License.

/*! *****************************************************************************
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0

THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.

See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
***************************************************************************** */

#nullable enable
using System;
using System.Diagnostics.CodeAnalysis;
using Trungnt2910.Browser.Generators;

namespace Trungnt2910.Browser.Dom;

#pragma warning disable CS0108, CS8764, CS8766
/// <summary>
/// An iterator over the members of a list of the nodes in a subtree of the DOM. The nodes will be returned in document order.
/// </summary>
[JsObject]
public partial class NodeIterator: JsObject
{
    
    /// <summary>
    /// To be added.
    /// </summary>
    public Union<JsFunc<Node?, double?>, InlineHasAcceptNode>? Filter
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<Union<JsFunc<Node?, double?>, InlineHasAcceptNode>>.ValueOrNullFromJs($"{_jsThis}.filter");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public bool? PointerBeforeReferenceNode
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.boolOrNullFromJs($"{_jsThis}.pointerBeforeReferenceNode");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public Node? ReferenceNode
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<Node>.ValueOrNullFromJs($"{_jsThis}.referenceNode");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public Node? Root
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<Node>.ValueOrNullFromJs($"{_jsThis}.root");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? WhatToShow
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.whatToShow");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    [global::System.Obsolete]
    public void Detach() => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.detach()");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public Node? NextNode() => global::Trungnt2910.Browser.WebAssemblyRuntime<Node>.ValueOrNullFromJs($"{_jsThis}.nextNode()");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public Node? PreviousNode() => global::Trungnt2910.Browser.WebAssemblyRuntime<Node>.ValueOrNullFromJs($"{_jsThis}.previousNode()");
    
}
#pragma warning restore CS0108, CS8764, CS8766

