// This file was generated by "LibDomTypeScriptParser, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", from "lib.dom.d.ts".
// Do not edit directly. If you encounter any bugs, please fix the generator's code.
//
// Copyright (C) 2023 Trung Nguyen. All rights reserved.
// Licensed under the MIT License.

/*! *****************************************************************************
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0

THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.

See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
***************************************************************************** */

#nullable enable
using System;
using System.Diagnostics.CodeAnalysis;
using Trungnt2910.Browser.Generators;

namespace Trungnt2910.Browser.Dom;

#pragma warning disable CS0108, CS8764, CS8766
/// <summary>
/// To be added.
/// </summary>
[JsObject]
public partial class PublicKeyCredentialCreationOptions: JsObject
{
    
    /// <summary>
    /// To be added.
    /// </summary>
    public string? Attestation
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.StringOrNullFromJs($"{_jsThis}.attestation");
        set => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.attestation = {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(value))}");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public AuthenticatorSelectionCriteria? AuthenticatorSelection
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<AuthenticatorSelectionCriteria>.ValueOrNullFromJs($"{_jsThis}.authenticatorSelection");
        set => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.authenticatorSelection = {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(value))}");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public Union<ArrayBufferView, ArrayBuffer>? Challenge
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<Union<ArrayBufferView, ArrayBuffer>>.ValueOrNullFromJs($"{_jsThis}.challenge");
        set => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.challenge = {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(value))}");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public JsArray<PublicKeyCredentialDescriptor>? ExcludeCredentials
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<JsArray<PublicKeyCredentialDescriptor>>.ValueOrNullFromJs($"{_jsThis}.excludeCredentials");
        set => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.excludeCredentials = {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(value))}");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public AuthenticationExtensionsClientInputs? Extensions
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<AuthenticationExtensionsClientInputs>.ValueOrNullFromJs($"{_jsThis}.extensions");
        set => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.extensions = {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(value))}");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public JsArray<PublicKeyCredentialParameters>? PubKeyCredParams
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<JsArray<PublicKeyCredentialParameters>>.ValueOrNullFromJs($"{_jsThis}.pubKeyCredParams");
        set => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.pubKeyCredParams = {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(value))}");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public PublicKeyCredentialRpEntity? Rp
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<PublicKeyCredentialRpEntity>.ValueOrNullFromJs($"{_jsThis}.rp");
        set => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.rp = {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(value))}");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? TimeOut
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.timeout");
        set => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.timeout = {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(value))}");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public PublicKeyCredentialUserEntity? User
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<PublicKeyCredentialUserEntity>.ValueOrNullFromJs($"{_jsThis}.user");
        set => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.user = {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(value))}");
    }
    
}
#pragma warning restore CS0108, CS8764, CS8766

