// This file was generated by "LibDomTypeScriptParser, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", from "lib.dom.d.ts".
// Do not edit directly. If you encounter any bugs, please fix the generator's code.
//
// Copyright (C) 2023 Trung Nguyen. All rights reserved.
// Licensed under the MIT License.

/*! *****************************************************************************
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0

THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.

See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
***************************************************************************** */

#nullable enable
using System;
using System.Diagnostics.CodeAnalysis;
using Trungnt2910.Browser.Generators;

namespace Trungnt2910.Browser.Dom;

#pragma warning disable CS0108, CS8764, CS8766
/// <summary>
/// This Push API interface provides a subcription's URL endpoint and allows unsubscription from a push service.
/// Available only in secure contexts.
/// </summary>
[JsObject]
public partial class PushSubscription: JsObject
{
    
    /// <summary>
    /// To be added.
    /// </summary>
    public string? Endpoint
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.StringOrNullFromJs($"{_jsThis}.endpoint");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? ExpirationTime
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.expirationTime");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public PushSubscriptionOptions? Options
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<PushSubscriptionOptions>.ValueOrNullFromJs($"{_jsThis}.options");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public ArrayBuffer? GetKey(string? name) => global::Trungnt2910.Browser.WebAssemblyRuntime<ArrayBuffer>.ValueOrNullFromJs($"{_jsThis}.getKey({(global::Trungnt2910.Browser.JsObject.ToJsObjectString(name))})");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public PushSubscriptionJSON? ToJSON() => global::Trungnt2910.Browser.WebAssemblyRuntime<PushSubscriptionJSON>.ValueOrNullFromJs($"{_jsThis}.toJSON()");
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public Promise<bool>? Unsubscribe() => global::Trungnt2910.Browser.WebAssemblyRuntime<Promise<bool>>.ValueOrNullFromJs($"{_jsThis}.unsubscribe()");
    
}
#pragma warning restore CS0108, CS8764, CS8766

