// This file was generated by "LibDomTypeScriptParser, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", from "lib.dom.d.ts".
// Do not edit directly. If you encounter any bugs, please fix the generator's code.
//
// Copyright (C) 2022 Trung Nguyen. All rights reserved.
// Licensed under the MIT License.

/*! *****************************************************************************
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0

THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.

See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
***************************************************************************** */

#nullable enable
using System;
using System.Diagnostics.CodeAnalysis;
using Trungnt2910.Browser.Generators;

namespace Trungnt2910.Browser.Dom;

#pragma warning disable CS0108, CS8764, CS8766
/// <summary>
/// To be added.
/// </summary>
[JsObject]
public partial class Transformer<I, O>: JsObject
{
    
    /// <summary>
    /// To be added.
    /// </summary>
    public TransformerFlushCallback<O>? Flush
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<TransformerFlushCallback<O>>.ValueOrNullFromJs($"{_jsThis}.flush");
        set => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.flush = {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(value))}");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public TransformerStartCallback<O>? Start
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<TransformerStartCallback<O>>.ValueOrNullFromJs($"{_jsThis}.start");
        set => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.start = {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(value))}");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public TransformerTransformCallback<I, O>? Transform
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<TransformerTransformCallback<I, O>>.ValueOrNullFromJs($"{_jsThis}.transform");
        set => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.transform = {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(value))}");
    }
    
}
/// <summary>
/// To be added.
/// </summary>
[JsObject]
public partial class Transformer<I>: JsObject
{
    
    /// <summary>
    /// To be added.
    /// </summary>
    public TransformerFlushCallback<JsObject>? Flush
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<TransformerFlushCallback<JsObject>>.ValueOrNullFromJs($"{_jsThis}.flush");
        set => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.flush = {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(value))}");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public TransformerStartCallback<JsObject>? Start
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<TransformerStartCallback<JsObject>>.ValueOrNullFromJs($"{_jsThis}.start");
        set => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.start = {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(value))}");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public TransformerTransformCallback<I, JsObject>? Transform
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<TransformerTransformCallback<I, JsObject>>.ValueOrNullFromJs($"{_jsThis}.transform");
        set => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.transform = {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(value))}");
    }
    
}
/// <summary>
/// To be added.
/// </summary>
[JsObject]
public partial class Transformer: JsObject
{
    
    /// <summary>
    /// To be added.
    /// </summary>
    public TransformerFlushCallback<JsObject>? Flush
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<TransformerFlushCallback<JsObject>>.ValueOrNullFromJs($"{_jsThis}.flush");
        set => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.flush = {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(value))}");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public TransformerStartCallback<JsObject>? Start
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<TransformerStartCallback<JsObject>>.ValueOrNullFromJs($"{_jsThis}.start");
        set => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.start = {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(value))}");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public TransformerTransformCallback<JsObject, JsObject>? Transform
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime<TransformerTransformCallback<JsObject, JsObject>>.ValueOrNullFromJs($"{_jsThis}.transform");
        set => global::Trungnt2910.Browser.WebAssemblyRuntime.InvokeJS($"{_jsThis}.transform = {(global::Trungnt2910.Browser.JsObject.ToJsObjectString(value))}");
    }
    
}
#pragma warning restore CS0108, CS8764, CS8766

