// This file was generated by "LibDomTypeScriptParser, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", from "lib.dom.d.ts".
// Do not edit directly. If you encounter any bugs, please fix the generator's code.
//
// Copyright (C) 2023 Trung Nguyen. All rights reserved.
// Licensed under the MIT License.

/*! *****************************************************************************
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0

THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.

See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
***************************************************************************** */

#nullable enable
using System;
using System.Diagnostics.CodeAnalysis;
using Trungnt2910.Browser.Generators;

namespace Trungnt2910.Browser.Dom;

#pragma warning disable CS0108, CS8764, CS8766
/// <summary>
/// To be added.
/// </summary>
[JsObject]
public partial class WEBGL_compressed_texture_etc: JsObject
{
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? COMPRESSED_R11_EAC
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.COMPRESSED_R11_EAC");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? COMPRESSED_RG11_EAC
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.COMPRESSED_RG11_EAC");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? COMPRESSED_RGB8_ETC2
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.COMPRESSED_RGB8_ETC2");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? COMPRESSED_RGBA8_ETC2_EAC
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.COMPRESSED_RGBA8_ETC2_EAC");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? COMPRESSED_SIGNED_R11_EAC
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.COMPRESSED_SIGNED_R11_EAC");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? COMPRESSED_SIGNED_RG11_EAC
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.COMPRESSED_SIGNED_RG11_EAC");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? COMPRESSED_SRGB8_ALPHA8_ETC2_EAC
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.COMPRESSED_SRGB8_ALPHA8_ETC2_EAC");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? COMPRESSED_SRGB8_ETC2
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.COMPRESSED_SRGB8_ETC2");
    }
    
    
    /// <summary>
    /// To be added.
    /// </summary>
    public double? COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2
    {
        get => global::Trungnt2910.Browser.WebAssemblyRuntime.doubleOrNullFromJs($"{_jsThis}.COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2");
    }
    
}
#pragma warning restore CS0108, CS8764, CS8766

