name: CI

on:
  create:
    branches:
      - release/**
  push:
    branches:
    - master
    - dev/**
  pull_request:
    branches:
    - master
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.10
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.10

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Setup .NET
      run: |
        Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -OutFile 'dotnet-install.ps1'
        ./dotnet-install.ps1 -Channel Current
      shell: pwsh

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore tools
      run: dotnet tool restore

    - name: Build and install workload
      run: dotnet cake build.cake --target=InstallWorkload --configuration=$env:BUILD_CONFIG --build-version=${{ steps.gitversion.outputs.majorMinorPatch }} --package-version=${{ steps.gitversion.outputs.semVer }}

    - name: Build and publish sample app
      run: dotnet publish sample/Trungnt2910.Browser.Sample/Trungnt2910.Browser.Sample.csproj --configuration $env:BUILD_CONFIG -p:Version=${{ steps.gitversion.outputs.assemblySemVer }} --framework=net6.0-browser

    - name: Publish sample app artifact
      uses: actions/upload-artifact@v1
      with:
        name: sample_app
        path: sample/Trungnt2910.Browser.Sample/bin/${{ env.BUILD_CONFIG }}/net6.0-browser/win-x64/publish

    - name: Publish nuget artifacts
      uses: actions/upload-artifact@v2
      with:
        name: packages.${{ steps.gitversion.outputs.semVer }}
        path: out/nuget/**

    # - name: Publish dev
    #   if: github.ref == 'refs/heads/master'
    #   run: nuget push .nupkgs\** -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}

    # - name: Publish
    #   if: startsWith(github.ref, 'refs/heads/release')
    #   run: nuget push .nupkgs\** -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download sample app artifact
      uses: actions/download-artifact@v1
      with:
        name: sample_app

    - name: Deploy sample to GitHub pages
      uses: JamesIves/github-pages-deploy-action@v4
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        folder: sample_app
        clean-exclude: pr-preview/
        force: false

    - name: Deploy sample PR preview
      uses: rossjrw/pr-preview-action@v1
      if: ${{ github.event_name == 'pull_request' }}
      with:
        source-dir: sample_app